[package]
name = "sfml-gameboy"
version = "0.1.0"
authors = ["Adam Casey <adamncasey@gmail.com>"]
edition = "2018"

[dependencies]
sfml = "*"
clap = "*"
gameboy = { path = "../gameboy" }

[profile.release]
debug = true